server:
   port: 80
cors:
   originPatters: http://localhost:3000,http://localhost:8080
file:
   upload-dir: C:/uploadDir
email:
   subject: "Default Subject"
   message: "Default Message"
security:
   jwt:
      token:
         secret-key: 53cr37
         expire-length: 3600000
spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/rest_spring_boot_api?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=Africa/Maputo
      username: root
      password: 
   jpa:
      hibernate:
         ddl-auto: none
      properties:
        hibernate:
           dialect: org.hibernate.dialect.MySQLDialect
        show-sql: false
   mail: 
      host: mail.bluteki.com
      port: 587
      username: ${EMAIL_USERNAME}
      password: ${EMAIL_PASSWORD}
      properties:
         mail.smtp.auth: true
         mail.smtp.starttls.enable: true
         mail.smtp.starttls.required: true

   servlet:
      multipart:
         enabled: true
         file-size-threshold: 2KB
         max-file-size: 200MB
         max-request-size: 215MB
logging:
   level:
      com.maculuve: INFO
springdoc:
   paths-to-match:
      -  /auth/**
      - /api/v1/**
   swagger-ui:
      use-root-path: true

        