cors:
   originPatters: http://localhost:3000,http://localhost:8080
file:
   upload-dir: <PATH_UPLOAD>
email:
   subject: "Default Subject"
   message: "Default Message"
security:
   jwt:
      token:
         secret-key: <SECRET_KEY>
         expire-length: <TIME EXPIRE
spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/<YOUR_DB>?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
      username: <USERNAME_DB>
      password: <PASSWORD>
   jpa:
      hibernate:
         ddl-auto: none
      properties:
        hibernate:
           dialect: org.hibernate.dialect.MySQLDialect
        show-sql: false
   mail: 
      host: <HOST_MAIL>
      port: 587
      username: ${EMAIL_USERNAME}
      password: ${EMAIL_PASSWORD}
      properties:
         mail.smtp.auth: true
         mail.smtp.starttls.enable: true
         mail.smtp.starttls.required: true
   servlet:
      multipart:
         enabled: true
         file-size-threshold: 2KB
         max-file-size: 200MB
         max-request-size: 215MB
logging:
   level:
      # root: WARN
      com.maculuve: DEBUG
springdoc:
   pathsToMatch: 
      -  /auth/**
      - /api/v1/**
   swagger-ui:
      use-root-path: true

        