cors:
   originPatters: http://localhost:3000,http://localhost:8080
   jwt:
      token:
         secret-key: <SECRET_KEY>
         expire-length: <TIME EXPIRE
spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/<YOUR_DB>?createDatabaseIfNotExist=true
      username: <USERNAME_DB>
      password: <PASSWORD>
   jpa:
      hibernate:
         ddl-auto: none
      properties:
        hibernate:
           dialect: org.hibernate.dialect.MySQLDialect
        show-sql: false
springdoc:
   pathsToMatch: 
      -  /auth/**
      - /api/v1/**
   swagger-ui:
      use-root-path: true

        