name: Continuous Integration and Delivery with Github Actions

on:
  push:
    - "main"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
   
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ASCCESS_TOKEN }}

    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin' # See 'Supported distributions' for available options
        canche: maven
